version: "3.9"
services:
    mongodb:
        image: mongo
        container_name: mongodb
        ports:
            - 27017:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=rootuser
            - MONGO_INITDB_ROOT_PASSWORD=rootpass

networks:
    default:
        name: mongodb_network
